### ISSUE TITLE
unreachable code panic

### ISSUE THREAD

**Issue by jonathanstrong** [rhaiscript/rhai#532] opened 2022-03-03 23:16 UTC
I can't make much sense of this, but thought it might be helpful to see...

```
thread 'main' panicked at 'internal error: entered unreachable code: invalid dot expression: 1644210000000000000..1644296400000000000 @ 10:15', /home/jstrong/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.5.0/src/eval/chaining.rs:803:17
stack backtrace:
   0:     0x559900d9638c - std::backtrace_rs::backtrace::libunwind::trace::hc3fd1c9c7c4d0cee
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x559900d9638c - std::backtrace_rs::backtrace::trace_unsynchronized::h1bcb748e1dcce1e1
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559900d9638c - std::sys_common::backtrace::_print_fmt::h1cd1f453c2c87c8f
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x559900d9638c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3466c9885d3b634a
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x559900dbbe8c - core::fmt::write::h15a53a6ce929975b
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/core/src/fmt/mod.rs:1190:17
   5:     0x559900d92188 - std::io::Write::write_fmt::h99e83eb16492984c
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/io/mod.rs:1657:15
   6:     0x559900d98577 - std::sys_common::backtrace::_print::haf3b28e74b66955d
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x559900d98577 - std::sys_common::backtrace::print::h604cc152112832c7
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x559900d98577 - std::panicking::default_hook::{{closure}}::h024c2c76012ae79e
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:295:22
   9:     0x559900d9822f - std::panicking::default_hook::h5de412011f5991b9
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:314:9
  10:     0x559900d98ccb - std::panicking::rust_panic_with_hook::h3547b52aec901adc
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:698:17
  11:     0x559900d989b7 - std::panicking::begin_panic_handler::{{closure}}::he82cec24741fa705
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:588:13
  12:     0x559900d96854 - std::sys_common::backtrace::__rust_end_short_backtrace::ha9806a9597fe04bd
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x559900d986c9 - rust_begin_unwind
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:584:5
  14:     0x559900885db3 - core::panicking::panic_fmt::hb3e80edb0c593161
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/core/src/panicking.rs:142:14
  15:     0x559900c3a5de - rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain_arguments::heada5945346ef0f0
  16:     0x559900c39d19 - rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain::h8d98b154b0e5cbfc
  17:     0x559900c43ee6 - rhai::eval::expr::<impl rhai::engine::Engine>::eval_expr::h3d0db46a93589d3b
  18:     0x559900c48221 - rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt::h43a8a8ea70ccc343
  19:     0x559900c457ee - rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block::h760fd3bfd20dac43
  20:     0x5599008a0e40 - hello_rhai::main::hdf20e941f0e379d1
  21:     0x55990088f853 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd7c804f5659b7669
  22:     0x5599008968dd - std::rt::lang_start::{{closure}}::h3bf61c64dc8a7502
  23:     0x559900d95a41 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h85be4bc44c8c4358
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/core/src/ops/function.rs:259:13
  24:     0x559900d95a41 - std::panicking::try::do_call::h7c662162d2eb01ca
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:492:40
  25:     0x559900d95a41 - std::panicking::try::hfa5c5460a03aebaa
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:456:19
  26:     0x559900d95a41 - std::panic::catch_unwind::h91eb89ae7bfdb166
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panic.rs:137:14
  27:     0x559900d95a41 - std::rt::lang_start_internal::{{closure}}::h70056cdb2a8d0eb6
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/rt.rs:128:48
  28:     0x559900d95a41 - std::panicking::try::do_call::h68b1e45871470f71
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:492:40
  29:     0x559900d95a41 - std::panicking::try::h678794b2c10c36a4
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panicking.rs:456:19
  30:     0x559900d95a41 - std::panic::catch_unwind::hbaf5c9b8fe069901
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/panic.rs:137:14
  31:     0x559900d95a41 - std::rt::lang_start_internal::he7abf2813591e8a1
                               at /rustc/45e2c2881d11324d610815bfff097e25c412199e/library/std/src/rt.rs:128:20
  32:     0x5599008a8ef2 - main
  33:     0x7f3480e3d0b3 - __libc_start_main
                               at /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
  34:     0x55990088665e - _start
  35:                0x0 - <unknown>
```

**update** fwiw, this appears to be caused by a line of code with the result of function calls passed to a function. both functions used on the line are rust/registered functions.

```rust
fn ymd(i32, u32, u32) -> i64 { /* .. */ }

// in MyCollectionWrapper impl block:
fn range(&mut self, i64, i64) -> Self { /* .. */ }
```

rhai:
```rhai
let ys = xs.range(ymd(2022, 2, 1), ymd(2022, 2, 2));
```

the crash does not happen if I store the `ymd` calls into local vars:

```
let start = ymd(2022, 2, 1);
let end = ymd(2022, 2, 2);
xs.range(start, end); // panic-free
```

**Comment by schungx** [comment] 2022-03-04 01:54
Any panic is a bug, so this should be a bug.  Let me check it out.

**Comment by jonathanstrong** [comment] 2022-03-04 03:05
here is an isolated example: https://gist.github.com/jonathanstrong/9431e5ca238f6ad544d8051744e595ea

the problem seems to be related to the name `range`. if I change it to `range2`, the code runs fine.

**Comment by schungx** [comment] 2022-03-04 03:13
Yes, `range` is a built-in function.  Obviously some code is unexpectedly optimizing it to the `..` operator.

I rolled it back to `1.5` and tried it but I still cannot reproduce the error...

**Comment by schungx** [comment] 2022-03-04 03:18
You might want to `Engine::compile` a minimal code segment and the debug-print the `AST`...  then I can probably see what's going on.

**Comment by schungx** [comment] 2022-03-04 03:23
That's it.  Full optimizations is the culprit:

`engine.set_optimization_level(rhai::OptimizationLevel::Full);`

**Comment by schungx** [comment] 2022-03-04 03:51
There is a bug in the optimizer.  It should not eager-evaluate method calls.  It'll be fixed in the next release.

BTW, is there any particular reason why you need full optimizations?  The default `Simple` usually works fine unless you have large amounts of function calls on constants (such as `ymd`).

**Comment by jonathanstrong** [comment] 2022-03-04 07:27
> BTW, is there any particular reason why you need full optimizations?

not particularly, I added that when assessing performance of applying a function to a large data set (other thread).

**Comment by schungx** [comment] 2022-03-04 07:43
> not particularly, I added that when assessing performance of applying a function to a large data set (other thread).

It is useful only if you call a lot of functions that have constant behavior (e.g. your `ymd`).  Otherwise, it is not a route that is well-tested as not many users turn it on...

**Comment by schungx** [comment] 2022-03-04 14:58
Closing this for now, as the fix will go in the next release.  Feel free to reopen if you still have problems.

**Closed by schungx** 2022-03-04 14:58 UTC
Labels: bug
