### ISSUE TITLE
cannot find function `supports_feature` in crate `rustc`

### ISSUE THREAD

**Issue by youngzhaozju** [rhaiscript/rhai#578] opened 2022-06-25 03:06 UTC
Hey, 
In the test mode, I found the following error using version 1.7, 1.6...
But, out of the test mode, the error was not reported.

#[cfg(test)]
mod tests {
    #[test]
    fn t() {}
}

error[E0425]: cannot find function `supports_feature` in crate `rustc`
 --> C:\Users\admin\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\smartstring-1.0.1\./build.rs:9:44
  |
9 |     let has_feature = Some(true) == rustc::supports_feature("allocator_api");
  |                                            ^^^^^^^^^^^^^^^^ not found in `rustc`

if I remove the following from toml, there will be no error.
rhai =  { version = "1.5.0", features = ["sync","unicode-xid-ident"] }

Thank you!
Regards,
Yang

**Comment by schungx** [comment] 2022-06-25 03:10
What is your compiler version?

Rhai requires 1.57 mainly because of `SmartString`.

**Comment by youngzhaozju** [comment] 2022-06-25 03:20
> 

Dear schungx,
Thanks for your supper fast reply, as you always did!

 rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.61.0 (fe5b13d68 2022-05-18)`

Thank you!
Yang

**Comment by schungx** [comment] 2022-07-01 06:03
@youngzhaozju   Do you still have this problem?  Because I don't seem to be able to reproduce it...

Maybe you can do a `cargo update` to refresh your `Cargo.lock`?

This can be a dependency version problem.

**Comment by youngzhaozju** [comment] 2022-07-04 02:51
> @youngzhaozju Do you still have this problem? Because I don't seem to be able to reproduce it...
> 
> Maybe you can do a `cargo update` to refresh your `Cargo.lock`?
> 
> This can be a dependency version problem. The `version_check` crate needs to be version 0.9.4.

@schungx I still haven't solve this problem. I tried cargo update but it was not helpful. I think it might be caused by conflicting crates. I will report it if I found any solution. Thank you!

**Comment by schungx** [comment] 2022-07-20 10:11
Did you end up resolving  your problem?

**Comment by schungx** [comment] 2022-07-22 00:56
Closing this for now.  Feel free to reopen if you still have prob.

**Closed by schungx** 2022-07-22 00:56 UTC
Labels: question
