### ISSUE TITLE
Cannot access `global` inside a callback closure

### ISSUE THREAD

**Issue by RazrFalcon** [rhaiscript/rhai#480] opened 2021-11-06 19:43 UTC
I have global function implemented something like this:

```rust
engine.register_result_fn("do_stuff",
    move |context: rhai::NativeCallContext, callback: rhai::FnPtr| {
        callback.call_dynamic(&context, None, [])
    }
);
```

In a Rhai script, when I'm trying to access a global variable using `global::SOME_VALUE` I'm getting:

```
Variable not found: global (line 40, position 34) in call to function read_data (line 22, position 14)
```

The strange part is that it works just fine for Rhai native closures, like:

```rust
const SOME_VALUE = 42;

fn do_stuff(f) {
    f.call();
}

fn run() {
    do_stuff(|| {
        print(global::SOME_VALUE); // This works
    });
}

run();
```

Is it a bug or a known limitation?

**Comment by schungx** [comment] 2021-11-07 03:18
I'll take a look at this...

**Comment by schungx** [comment] 2021-11-07 09:27
It seems to be a limitation of the current engine structure.  I'll see if there is a way to lift this limit.

**Comment by RazrFalcon** [comment] 2021-11-07 17:14
Turns out it does work, but I had to disable the `no_module` feature. It's strange that it partially works even without it.

**Comment by schungx** [comment] 2021-11-08 01:09
Yes, that's correct.  With `no_module` the parser won't recognize the `module::variable` syntax, therefore you won't be able to parse the script in the first place.

It used to work before, but the `Engine` internals were modified a couple of releases ago which caused this break.

I'll put out a new release which reverses this regression.

I'm marking this issue as `bug`.

**Comment by RazrFalcon** [comment] 2021-11-08 11:26
It works for functions, but not closures. No idea why functions can process the `global::` module even with `no_module`.

**Comment by schungx** [comment] 2022-01-23 14:59
Closing this for now.  Feel free to reopen if it is still not working correctly.

**Closed by schungx** 2022-01-23 14:59 UTC
Labels: question
